#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 19 20:27:07 2021

@author: erick
"""

import numpy as np
import matplotlib.pyplot as plt
import functions as f

I = plt.imread('/media/erick/NuevoVol/LINUX_LAP/PhD/GT_200821/Cell_1/10um_150steps/1500 _Ecoli_HCB1_10x_50Hz_0.050ms_642nm_frame_stack_150steps_10um/1500 _Ecoli_HCB1_10x_50Hz_0.050ms_642nm_frame_stack_150steps_10um_z0_frame97.png')
I = plt.imread('/media/erick/NuevoVol/LINUX_LAP/PhD/Archea_LW/20x_ArchFM1_30Hz_150us_1_2000frames_BS.png')

I_MEDIAN = np.ones_like(I)
N = 1.3226
LAMBDA = 0.642              # HeNe
MPP = 10 
FS = 0.711                     # Sampling Frequency px/um
SZ = 5    

rs = f.rayleighSommerfeldPropagator(I, I_MEDIAN, N, LAMBDA, FS, SZ, 100)
_, BINS = np.histogram(rs.flatten())
rs[rs < BINS[8]] = 0


gs = f.modified_propagator(I, I_MEDIAN, N, LAMBDA, FS, SZ, 100)

#%% Export LUT
path = '/media/erick/NuevoVol/LINUX_LAP/PhD/Archea_LW/LUT/'

ci, cj = 71, 399
D = 22

for i in range(40):
    plt.imsave(path+np.str(i)+'.png', rs[ci-D:ci+D, cj-D:cj+D , i], cmap='gray')   