#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  9 20:57:39 2020

@author: erick
"""
import os
import numpy as np
import pandas as pd

PATH = '/media/erick/NuevoVol/LINUX_LAP/PhD/Colloids/20x_50Hz_100us_642nm_colloids_2000frames_2000frames_rayleighSommerfeld_Results_smooth.csv'
path = '/home/erick/Documents/PhD/Holography-Code/Tracks_LW/'

file_list = os.listdir(path)
particle_positions = np.ones((1, 8))
for i in range(len(file_list)):
    raw_data = np.loadtxt(path+file_list[i])
    data = np.hstack((raw_data, i*np.ones((len(raw_data), 1))))
    particle_positions = np.vstack((particle_positions, data))

particle_positions = particle_positions[1:, :]

particle_positions_df = pd.DataFrame(particle_positions, columns=['FRAME', 'X', 'Y', 'Z', 'Xm', 'Ym', 'Zm', 'PARTICLE'])

#%% Plotly scatter plot
import plotly.express as px
import pandas as pd
from plotly.offline import plot

# CURVE= = LINKED[LINKED.PARTICLE != -1]
# CURVE = pd.DataFrame(), columns=['X', 'Y', 'Z', 'PARTICLE'])


# fig = px.scatter_3d(CURVE, x='X', y='Y', z='Z', color='PARTICLE')
fig = px.line_3d(particle_positions_df, x='Xm', y='Ym', z='Zm', color='PARTICLE')
fig.update_traces(marker=dict(size=1))
plot(fig)

particle_positions_rs_df = pd.read_csv(PATH)
particle_positions_rs_df = particle_positions_rs_df[particle_positions_rs_df.PARTICLE != -1]
fig1 = px.line_3d(particle_positions_rs_df, x='X', y='Y', z='Z', color='PARTICLE')
fig1.update_traces(marker=dict(size=1))
plot(fig1)


#%% Plot with plotly.graph_objects
import plotly.graph_objects as go
from plotly.offline import plot
from plotly.subplots import make_subplots


# PATH = '/home/erick/Documents/PhD/Colloids/20x_50Hz_100us_642nm_colloids_2000frames_2000frames_rayleighSommerfeld_Results_smooth.csv'
PATH = '/media/erick/NuevoVol/LINUX_LAP/PhD/Colloids/20x_50Hz_100us_642nm_colloids_2000frames_2000frames_rayleighSommerfeld_Results_smooth.csv'

# P_RS = particle_positions_df
P_MOD = pd.read_csv(PATH)


fig = make_subplots(
    rows=1, cols=2,
    specs=[[{"type": "scatter3d"}, {"type": "scatter3d"}]])


fig.add_trace(go.Scatter3d(x=P_MOD['X'], y=P_MOD['Y'], 
                            z=P_MOD['Z'], mode="markers", 
                            marker=dict(
                                size=1,
                                color=P_MOD['PARTICLE'].values,
                                colorscale='Viridis'
                                )),
              row=1, col=1)

fig.add_trace(go.Scatter3d(x=P_MOD['X'], y=P_MOD['Y'], 
                            z=P_MOD['Z'], mode="markers",
                            marker=dict(
                                size=1,
                                color=P_MOD['PARTICLE'].values,
                                colorscale='Viridis'
                                )),
              row=1, col=2)

fig.update_layout(height=900, width=1800, title_text="Propagator Comparison")
fig.show()
plot(fig)

#%%
import plotly.graph_objects as go
from plotly.offline import plot
from plotly.subplots import make_subplots

PATH = '/media/erick/NuevoVol/LINUX_LAP/PhD/Colloids/20x_50Hz_100us_642nm_colloids_2000frames_2000frames_rayleighSommerfeld_Results_smooth.csv'




